// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Categorium struct {
	IDCat          int32         `json:"id_cat"`
	NombreCat      string        `json:"nombre_cat"`
	DescripcionCat string        `json:"descripcion_cat"`
	IDPadre        sql.NullInt32 `json:"id_padre"`
	CreatedAt      sql.NullTime  `json:"created_at"`
}

type Producto struct {
	IDProd          int32        `json:"id_prod"`
	NombreProd      string       `json:"nombre_prod"`
	DescripcionProd string       `json:"descripcion_prod"`
	Precio          string       `json:"precio"`
	Stock           int32        `json:"stock"`
	IDCat           int32        `json:"id_cat"`
	CreatedAt       sql.NullTime `json:"created_at"`
}
