// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createCategoria = `-- name: CreateCategoria :one
INSERT INTO categoria(nombre_cat, descripcion_cat, id_padre)
VALUES ($1, $2, $3)
RETURNING id_cat, nombre_cat, descripcion_cat, id_padre, created_at
`

type CreateCategoriaParams struct {
	NombreCat      string        `json:"nombre_cat"`
	DescripcionCat string        `json:"descripcion_cat"`
	IDPadre        sql.NullInt32 `json:"id_padre"`
}

func (q *Queries) CreateCategoria(ctx context.Context, arg CreateCategoriaParams) (Categorium, error) {
	row := q.db.QueryRowContext(ctx, createCategoria, arg.NombreCat, arg.DescripcionCat, arg.IDPadre)
	var i Categorium
	err := row.Scan(
		&i.IDCat,
		&i.NombreCat,
		&i.DescripcionCat,
		&i.IDPadre,
		&i.CreatedAt,
	)
	return i, err
}

const createProducto = `-- name: CreateProducto :one
INSERT INTO producto (nombre_prod, descripcion_prod, precio, stock, id_cat)
VALUES ($1, $2, $3, $4, $5)
RETURNING id_prod, nombre_prod, descripcion_prod, precio, stock, id_cat created_at
`

type CreateProductoParams struct {
	NombreProd      string `json:"nombre_prod"`
	DescripcionProd string `json:"descripcion_prod"`
	Precio          string `json:"precio"`
	Stock           int32  `json:"stock"`
	IDCat           int32  `json:"id_cat"`
}

type CreateProductoRow struct {
	IDProd          int32  `json:"id_prod"`
	NombreProd      string `json:"nombre_prod"`
	DescripcionProd string `json:"descripcion_prod"`
	Precio          string `json:"precio"`
	Stock           int32  `json:"stock"`
	CreatedAt       int32  `json:"created_at"`
}

func (q *Queries) CreateProducto(ctx context.Context, arg CreateProductoParams) (CreateProductoRow, error) {
	row := q.db.QueryRowContext(ctx, createProducto,
		arg.NombreProd,
		arg.DescripcionProd,
		arg.Precio,
		arg.Stock,
		arg.IDCat,
	)
	var i CreateProductoRow
	err := row.Scan(
		&i.IDProd,
		&i.NombreProd,
		&i.DescripcionProd,
		&i.Precio,
		&i.Stock,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategoria = `-- name: DeleteCategoria :exec
DELETE FROM categoria
WHERE id_cat = $1
`

func (q *Queries) DeleteCategoria(ctx context.Context, idCat int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategoria, idCat)
	return err
}

const deleteProducto = `-- name: DeleteProducto :exec
DELETE FROM producto
WHERE id_prod = $1
`

func (q *Queries) DeleteProducto(ctx context.Context, idProd int32) error {
	_, err := q.db.ExecContext(ctx, deleteProducto, idProd)
	return err
}

const getCategoria = `-- name: GetCategoria :one
SELECT id_cat, nombre_cat, descripcion_cat, id_padre, created_at
FROM categoria
WHERE id_cat = $1
`

func (q *Queries) GetCategoria(ctx context.Context, idCat int32) (Categorium, error) {
	row := q.db.QueryRowContext(ctx, getCategoria, idCat)
	var i Categorium
	err := row.Scan(
		&i.IDCat,
		&i.NombreCat,
		&i.DescripcionCat,
		&i.IDPadre,
		&i.CreatedAt,
	)
	return i, err
}

const getProducto = `-- name: GetProducto :one
SELECT id_prod, nombre_prod, descripcion_prod, precio, stock, id_cat, created_at
FROM producto
WHERE id_prod = $1
`

func (q *Queries) GetProducto(ctx context.Context, idProd int32) (Producto, error) {
	row := q.db.QueryRowContext(ctx, getProducto, idProd)
	var i Producto
	err := row.Scan(
		&i.IDProd,
		&i.NombreProd,
		&i.DescripcionProd,
		&i.Precio,
		&i.Stock,
		&i.IDCat,
		&i.CreatedAt,
	)
	return i, err
}

const listCategorias = `-- name: ListCategorias :many
SELECT id_cat, nombre_cat, descripcion_cat,id_padre, created_at
FROM categoria
ORDER BY nombre_cat ASC
`

func (q *Queries) ListCategorias(ctx context.Context) ([]Categorium, error) {
	rows, err := q.db.QueryContext(ctx, listCategorias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Categorium
	for rows.Next() {
		var i Categorium
		if err := rows.Scan(
			&i.IDCat,
			&i.NombreCat,
			&i.DescripcionCat,
			&i.IDPadre,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductos = `-- name: ListProductos :many
SELECT id_prod, nombre_prod, descripcion_prod, precio, stock, id_cat, created_at
FROM producto
ORDER BY nombre_prod ASC
`

func (q *Queries) ListProductos(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.IDProd,
			&i.NombreProd,
			&i.DescripcionProd,
			&i.Precio,
			&i.Stock,
			&i.IDCat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductosByCategoria = `-- name: ListProductosByCategoria :many
SELECT id_prod, nombre_prod, descripcion_prod, precio, stock, id_cat, created_at
FROM producto
WHERE id_cat = $1
ORDER BY nombre_prod ASC
`

func (q *Queries) ListProductosByCategoria(ctx context.Context, idCat int32) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listProductosByCategoria, idCat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.IDProd,
			&i.NombreProd,
			&i.DescripcionProd,
			&i.Precio,
			&i.Stock,
			&i.IDCat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoria = `-- name: UpdateCategoria :exec
UPDATE categoria
SET nombre_cat = $2, descripcion_cat = $3
WHERE id_cat = $1
`

type UpdateCategoriaParams struct {
	IDCat          int32  `json:"id_cat"`
	NombreCat      string `json:"nombre_cat"`
	DescripcionCat string `json:"descripcion_cat"`
}

func (q *Queries) UpdateCategoria(ctx context.Context, arg UpdateCategoriaParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoria, arg.IDCat, arg.NombreCat, arg.DescripcionCat)
	return err
}

const updatePrecioProducto = `-- name: UpdatePrecioProducto :exec
UPDATE producto
SET precio = $2
WHERE id_prod = $1
`

type UpdatePrecioProductoParams struct {
	IDProd int32  `json:"id_prod"`
	Precio string `json:"precio"`
}

func (q *Queries) UpdatePrecioProducto(ctx context.Context, arg UpdatePrecioProductoParams) error {
	_, err := q.db.ExecContext(ctx, updatePrecioProducto, arg.IDProd, arg.Precio)
	return err
}

const updateProducto = `-- name: UpdateProducto :exec
UPDATE producto
SET nombre_prod = $2, descripcion_prod = $3, precio = $4, stock = $5
WHERE id_prod = $1
`

type UpdateProductoParams struct {
	IDProd          int32  `json:"id_prod"`
	NombreProd      string `json:"nombre_prod"`
	DescripcionProd string `json:"descripcion_prod"`
	Precio          string `json:"precio"`
	Stock           int32  `json:"stock"`
}

func (q *Queries) UpdateProducto(ctx context.Context, arg UpdateProductoParams) error {
	_, err := q.db.ExecContext(ctx, updateProducto,
		arg.IDProd,
		arg.NombreProd,
		arg.DescripcionProd,
		arg.Precio,
		arg.Stock,
	)
	return err
}

const updateStockProducto = `-- name: UpdateStockProducto :exec
UPDATE producto
SET stock = $2
WHERE id_prod = $1
`

type UpdateStockProductoParams struct {
	IDProd int32 `json:"id_prod"`
	Stock  int32 `json:"stock"`
}

func (q *Queries) UpdateStockProducto(ctx context.Context, arg UpdateStockProductoParams) error {
	_, err := q.db.ExecContext(ctx, updateStockProducto, arg.IDProd, arg.Stock)
	return err
}
