version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-tp
    environment:
      POSTGRES_USER: cliente
      POSTGRES_PASSWORD: progwebunicen
      POSTGRES_DB: mate_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d